### ISSUE TITLE
what is the correct procedure for importing react-native-macos

### ISSUE THREAD

**Issue by mrose17** [ptmt/react-native-touchbar#3]
i've already done `npm install react-native-macos-cli -g`

since you've already got a project here, what `react-native-macos ...` should be running and in which directory?

thanks!

**Comment by ptmt** [comment]
```
react-native-macos init MyProject
cd myProject
npm install react-native-touchbar
```

**Comment by mrose17** [comment]
facepalm (-; thank you!

**Comment by ptmt** [comment]
No problem. I recently have no chance to fix bugs and add new features. That is real facepalm. :(

**Comment by mrose17** [comment]
well, it is a good coding example... and perhaps others will contribute (-;

**Comment by 7kfpun** [comment]
Here is an example for your reference
https://github.com/7kfpun/FinanceMacOSReactNative

**Comment by mrose17** [comment]
many thanks! i will take a look...
