### ISSUE TITLE
No component found for view with name "RNTouchbar"

### ISSUE THREAD

**Issue by karaggeorge** [ptmt/react-native-touchbar#4]
I'm getting this error when running the application in the REAMDE.md file. Any idea how to solve it?

**Comment by ptmt** [comment]
You probably haven't linked it as a dependency to Xcode project http://facebook.github.io/react-native/releases/0.45/docs/linking-libraries-ios.html. Beware that this was a prototype, don't expect that something meaningful could be built with that without prior experience.
