### ISSUE TITLE
missing deps

### ISSUE THREAD

**Issue by sholzmayer** [ptmt/react-native-touchbar#6]
Could you please add the necessary dependencies to the package.json?

**Comment by ptmt** [comment]
Technically there is only one `peerDependency`: `react-native-macos`. But this was an experiment a few years ago, I'm not sure it's going to work now without any effort.

**Comment by sholzmayer** [comment]
i did a few fixes to the imports, now it works fine. It would be nice if you could merge it and update the npm registry afterwards :) 

Didn't added the peer deps.

**Comment by ptmt** [comment]
Would you mind sending a pull request?

**Comment by sholzmayer** [comment]
There you go #7
